# ######################################################################################################################
# AdvancedArmorStands Config
#
# Please do not delete anything in this file!
# For help please visit: https://github.com/Falyrion/AdvancedArmorStands
# ######################################################################################################################

# If true, armor stands will spawn with arms
spawnWithArms: true
# the max range, it should be bigger than 0 and smaller than 100
maxDistance: 10
